# Generated by Django 5.1.7 on 2025-03-10 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('shift', models.CharField(choices=[('A', 'Shift A (6:00 AM - 2:00 PM)'), ('B', 'Shift B (2:00 PM - 10:00 PM)'), ('C', 'Shift C (10:00 PM - 6:00 AM)'), ('G', 'General Shift (9:00 AM - 6:30 PM)')], max_length=1)),
                ('rake_id', models.CharField(help_text='Rake ID or Number', max_length=50)),
                ('material_type', models.CharField(choices=[('IRON_ORE', 'Iron Ore'), ('LIMESTONE', 'Limestone'), ('DOLOMITE', 'Dolomite'), ('COAL', 'Coal'), ('COKE', 'Coke'), ('OTHER', 'Other')], max_length=20)),
                ('supplier', models.CharField(help_text='Material supplier', max_length=100)),
                ('total_wagons', models.PositiveIntegerField(help_text='Total number of wagons')),
                ('wagon_capacity', models.DecimalField(decimal_places=2, help_text='Capacity per wagon in MT', max_digits=10)),
                ('total_quantity', models.DecimalField(decimal_places=2, help_text='Total quantity in MT', max_digits=10)),
                ('arrival_time', models.DateTimeField(help_text='Rake arrival time')),
                ('unloading_start_time', models.DateTimeField(help_text='Unloading start time')),
                ('unloading_end_time', models.DateTimeField(blank=True, help_text='Unloading end time', null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('UNLOADING', 'Unloading in Progress'), ('COMPLETED', 'Unloading Completed'), ('DISPATCHED', 'Dispatched')], default='RECEIVED', max_length=20)),
                ('unloading_equipment', models.CharField(help_text='Equipment used for unloading', max_length=50)),
                ('demurrage_hours', models.DecimalField(decimal_places=2, default=0, help_text='Demurrage hours if any', max_digits=5)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rake Report',
                'verbose_name_plural': 'Rake Reports',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
