# Generated by Django 5.1.7 on 2025-03-10 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('minimum_stock_level', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipment_type', models.CharField(choices=[('CONVEYOR', 'Conveyor'), ('STACKER', 'Stacker'), ('RECLAIMER', 'Reclaimer'), ('CRUSHER', 'Crusher'), ('SCREEN', 'Screen'), ('WAGON_TIPPLER', 'Wagon Tippler'), ('SIDE_ARM_CHARGER', 'Side Arm Charger'), ('OTHER', 'Other')], max_length=20)),
                ('maintenance_type', models.CharField(choices=[('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical'), ('INSTRUMENTATION', 'Instrumentation'), ('CIVIL', 'Civil'), ('OTHER', 'Other')], max_length=20)),
                ('last_restocked_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spare Part',
                'verbose_name_plural': 'Spare Parts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('shift', models.CharField(choices=[('A', 'Shift A (6:00 AM - 2:00 PM)'), ('B', 'Shift B (2:00 PM - 10:00 PM)'), ('C', 'Shift C (10:00 PM - 6:00 AM)'), ('G', 'General Shift (9:00 AM - 6:30 PM)')], max_length=1)),
                ('maintenance_type', models.CharField(choices=[('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical'), ('INSTRUMENTATION', 'Instrumentation'), ('CIVIL', 'Civil'), ('OTHER', 'Other')], max_length=20)),
                ('maintenance_category', models.CharField(choices=[('PREVENTIVE', 'Preventive Maintenance'), ('BREAKDOWN', 'Breakdown Maintenance'), ('CORRECTIVE', 'Corrective Maintenance'), ('PREDICTIVE', 'Predictive Maintenance'), ('ROUTINE', 'Routine Maintenance')], max_length=20)),
                ('area', models.CharField(choices=[('AREA_1', 'Area-1'), ('AREA_2', 'Area-2'), ('AREA_3', 'Area-3')], max_length=10)),
                ('equipment', models.CharField(choices=[('CONVEYOR', 'Conveyor'), ('STACKER', 'Stacker'), ('RECLAIMER', 'Reclaimer'), ('CRUSHER', 'Crusher'), ('SCREEN', 'Screen'), ('WAGON_TIPPLER', 'Wagon Tippler'), ('SIDE_ARM_CHARGER', 'Side Arm Charger'), ('OTHER', 'Other')], max_length=20)),
                ('equipment_id', models.CharField(help_text='Equipment ID or Tag Number', max_length=50)),
                ('activity_description', models.TextField(help_text='Description of maintenance activity')),
                ('spares_used', models.TextField(blank=True, help_text='Spares used for maintenance', null=True)),
                ('start_time', models.TimeField(help_text='Activity start time')),
                ('end_time', models.TimeField(help_text='Activity end time')),
                ('duration_hours', models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=5)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Activity',
                'verbose_name_plural': 'Maintenance Activities',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
