# Generated by Django 5.1.7 on 2025-03-11 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceactivity',
            name='activity_type',
            field=models.CharField(choices=[('PLANNED', 'Planned Activity'), ('EXECUTION', 'Execution Report')], default='PLANNED', max_length=10),
        ),
        migrations.AddField(
            model_name='maintenanceactivity',
            name='execution_description',
            field=models.TextField(blank=True, help_text='Description of actual work executed', null=True),
        ),
        migrations.AddField(
            model_name='maintenanceactivity',
            name='pending_work',
            field=models.TextField(blank=True, help_text='Description of pending work or jobs', null=True),
        ),
        migrations.AddField(
            model_name='maintenanceactivity',
            name='related_activity',
            field=models.ForeignKey(blank=True, help_text='Link to the related planning/execution activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_reports', to='maintenance.maintenanceactivity'),
        ),
        migrations.AddField(
            model_name='maintenanceactivity',
            name='spares_required',
            field=models.TextField(blank=True, help_text='Spares required for planned maintenance', null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceactivity',
            name='maintenance_type',
            field=models.CharField(choices=[('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical'), ('OPERATION', 'Operation'), ('CIVIL', 'Civil'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenanceactivity',
            name='spares_used',
            field=models.TextField(blank=True, help_text='Spares actually used in maintenance', null=True),
        ),
        migrations.AlterField(
            model_name='spare',
            name='maintenance_type',
            field=models.CharField(choices=[('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical'), ('OPERATION', 'Operation'), ('CIVIL', 'Civil'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
