# Generated by Django 5.1.7 on 2025-03-10 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area1Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('shift', models.CharField(choices=[('A', 'Shift A (6:00 AM - 2:00 PM)'), ('B', 'Shift B (2:00 PM - 10:00 PM)'), ('C', 'Shift C (10:00 PM - 6:00 AM)'), ('G', 'General Shift (9:00 AM - 6:30 PM)')], max_length=1)),
                ('reclaiming_material', models.CharField(choices=[('IRON_ORE', 'Iron Ore'), ('LIMESTONE', 'Limestone'), ('DOLOMITE', 'Dolomite'), ('COAL', 'Coal'), ('COKE', 'Coke'), ('SINTER', 'Sinter'), ('PELLET', 'Pellet'), ('OTHER', 'Other')], max_length=20)),
                ('reclaiming_quantity', models.DecimalField(decimal_places=2, help_text='Quantity in MT', max_digits=10)),
                ('reclaiming_equipment', models.CharField(help_text='Equipment used for reclaiming', max_length=50)),
                ('feeding_destination', models.CharField(help_text='Destination (BF/SMS)', max_length=50)),
                ('feeding_material', models.CharField(choices=[('IRON_ORE', 'Iron Ore'), ('LIMESTONE', 'Limestone'), ('DOLOMITE', 'Dolomite'), ('COAL', 'Coal'), ('COKE', 'Coke'), ('SINTER', 'Sinter'), ('PELLET', 'Pellet'), ('OTHER', 'Other')], max_length=20)),
                ('feeding_quantity', models.DecimalField(decimal_places=2, help_text='Quantity in MT', max_digits=10)),
                ('feeding_equipment', models.CharField(help_text='Equipment used for feeding', max_length=50)),
                ('receiving_source', models.CharField(help_text='Source (BF)', max_length=50)),
                ('receiving_material', models.CharField(choices=[('IRON_ORE', 'Iron Ore'), ('LIMESTONE', 'Limestone'), ('DOLOMITE', 'Dolomite'), ('COAL', 'Coal'), ('COKE', 'Coke'), ('SINTER', 'Sinter'), ('PELLET', 'Pellet'), ('OTHER', 'Other')], max_length=20)),
                ('receiving_quantity', models.DecimalField(decimal_places=2, help_text='Quantity in MT', max_digits=10)),
                ('receiving_equipment', models.CharField(help_text='Equipment used for receiving', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area1_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Area-1 Operation',
                'verbose_name_plural': 'Area-1 Operations',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Area23Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('shift', models.CharField(choices=[('A', 'Shift A (6:00 AM - 2:00 PM)'), ('B', 'Shift B (2:00 PM - 10:00 PM)'), ('C', 'Shift C (10:00 PM - 6:00 AM)'), ('G', 'General Shift (9:00 AM - 6:30 PM)')], max_length=1)),
                ('feeding_material', models.CharField(choices=[('IRON_ORE', 'Iron Ore'), ('LIMESTONE', 'Limestone'), ('DOLOMITE', 'Dolomite'), ('COAL', 'Coal'), ('COKE', 'Coke'), ('SINTER', 'Sinter'), ('PELLET', 'Pellet'), ('OTHER', 'Other')], max_length=20)),
                ('feeding_quantity', models.DecimalField(decimal_places=2, help_text='Quantity in MT', max_digits=10)),
                ('feeding_equipment', models.CharField(help_text='Equipment used for feeding', max_length=50)),
                ('receiving_material', models.CharField(choices=[('IRON_ORE', 'Iron Ore'), ('LIMESTONE', 'Limestone'), ('DOLOMITE', 'Dolomite'), ('COAL', 'Coal'), ('COKE', 'Coke'), ('SINTER', 'Sinter'), ('PELLET', 'Pellet'), ('OTHER', 'Other')], max_length=20)),
                ('receiving_quantity', models.DecimalField(decimal_places=2, help_text='Quantity in MT', max_digits=10)),
                ('receiving_equipment', models.CharField(help_text='Equipment used for receiving', max_length=50)),
                ('crushing_material', models.CharField(choices=[('IRON_ORE', 'Iron Ore'), ('LIMESTONE', 'Limestone'), ('DOLOMITE', 'Dolomite'), ('COAL', 'Coal'), ('COKE', 'Coke'), ('SINTER', 'Sinter'), ('PELLET', 'Pellet'), ('OTHER', 'Other')], max_length=20)),
                ('crushing_quantity', models.DecimalField(decimal_places=2, help_text='Quantity in MT', max_digits=10)),
                ('crushing_equipment', models.CharField(help_text='Equipment used for crushing', max_length=50)),
                ('base_mix_material', models.CharField(choices=[('IRON_ORE', 'Iron Ore'), ('LIMESTONE', 'Limestone'), ('DOLOMITE', 'Dolomite'), ('COAL', 'Coal'), ('COKE', 'Coke'), ('SINTER', 'Sinter'), ('PELLET', 'Pellet'), ('OTHER', 'Other')], max_length=20)),
                ('base_mix_quantity', models.DecimalField(decimal_places=2, help_text='Quantity in MT', max_digits=10)),
                ('base_mix_equipment', models.CharField(help_text='Equipment used for base mix handling', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area23_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Area-2 & 3 Operation',
                'verbose_name_plural': 'Area-2 & 3 Operations',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
