# Generated by Django 5.1.7 on 2025-03-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area1operation',
            name='feeding_other_equipment',
            field=models.CharField(blank=True, help_text='Specify if equipment is not standard', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area1operation',
            name='feeding_other_material',
            field=models.CharField(blank=True, help_text="Specify if 'Other' material is selected", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area1operation',
            name='receiving_other_equipment',
            field=models.CharField(blank=True, help_text='Specify if equipment is not standard', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area1operation',
            name='receiving_other_material',
            field=models.CharField(blank=True, help_text="Specify if 'Other' material is selected", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area1operation',
            name='reclaiming_other_equipment',
            field=models.CharField(blank=True, help_text='Specify if equipment is not standard', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area1operation',
            name='reclaiming_other_material',
            field=models.CharField(blank=True, help_text="Specify if 'Other' material is selected", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area23operation',
            name='base_mix_other_equipment',
            field=models.CharField(blank=True, help_text='Specify if equipment is not standard', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area23operation',
            name='base_mix_other_material',
            field=models.CharField(blank=True, help_text="Specify if 'Other' material is selected", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area23operation',
            name='crushing_other_equipment',
            field=models.CharField(blank=True, help_text='Specify if equipment is not standard', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area23operation',
            name='crushing_other_material',
            field=models.CharField(blank=True, help_text="Specify if 'Other' material is selected", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area23operation',
            name='feeding_other_equipment',
            field=models.CharField(blank=True, help_text='Specify if equipment is not standard', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area23operation',
            name='feeding_other_material',
            field=models.CharField(blank=True, help_text="Specify if 'Other' material is selected", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area23operation',
            name='receiving_other_equipment',
            field=models.CharField(blank=True, help_text='Specify if equipment is not standard', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='area23operation',
            name='receiving_other_material',
            field=models.CharField(blank=True, help_text="Specify if 'Other' material is selected", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='area1operation',
            name='feeding_material',
            field=models.CharField(choices=[('IRON_ORE', 'Iron Ore'), ('IRON_ORE_FINES', 'Iron Ore Fines'), ('LIMESTONE', 'Limestone'), ('DOLOMITE', 'Dolomite'), ('COAL', 'Coal'), ('COKE', 'Coke'), ('COKE_FINES', 'Coke Fines'), ('SINTER', 'Sinter'), ('SINTER_FINES', 'Sinter Fines'), ('PELLET', 'Pellet'), ('LUMP_ORE', 'Lump Ore'), ('QUARTZITE', 'Quartzite'), ('SLAG', 'Slag'), ('BASE_MIX', 'Base Mix'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='area1operation',
            name='receiving_material',
            field=models.CharField(choices=[('IRON_ORE', 'Iron Ore'), ('IRON_ORE_FINES', 'Iron Ore Fines'), ('LIMESTONE', 'Limestone'), ('DOLOMITE', 'Dolomite'), ('COAL', 'Coal'), ('COKE', 'Coke'), ('COKE_FINES', 'Coke Fines'), ('SINTER', 'Sinter'), ('SINTER_FINES', 'Sinter Fines'), ('PELLET', 'Pellet'), ('LUMP_ORE', 'Lump Ore'), ('QUARTZITE', 'Quartzite'), ('SLAG', 'Slag'), ('BASE_MIX', 'Base Mix'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='area1operation',
            name='reclaiming_material',
            field=models.CharField(choices=[('IRON_ORE', 'Iron Ore'), ('IRON_ORE_FINES', 'Iron Ore Fines'), ('LIMESTONE', 'Limestone'), ('DOLOMITE', 'Dolomite'), ('COAL', 'Coal'), ('COKE', 'Coke'), ('COKE_FINES', 'Coke Fines'), ('SINTER', 'Sinter'), ('SINTER_FINES', 'Sinter Fines'), ('PELLET', 'Pellet'), ('LUMP_ORE', 'Lump Ore'), ('QUARTZITE', 'Quartzite'), ('SLAG', 'Slag'), ('BASE_MIX', 'Base Mix'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='area23operation',
            name='base_mix_material',
            field=models.CharField(choices=[('IRON_ORE', 'Iron Ore'), ('IRON_ORE_FINES', 'Iron Ore Fines'), ('LIMESTONE', 'Limestone'), ('DOLOMITE', 'Dolomite'), ('COAL', 'Coal'), ('COKE', 'Coke'), ('COKE_FINES', 'Coke Fines'), ('SINTER', 'Sinter'), ('SINTER_FINES', 'Sinter Fines'), ('PELLET', 'Pellet'), ('LUMP_ORE', 'Lump Ore'), ('QUARTZITE', 'Quartzite'), ('SLAG', 'Slag'), ('BASE_MIX', 'Base Mix'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='area23operation',
            name='crushing_material',
            field=models.CharField(choices=[('IRON_ORE', 'Iron Ore'), ('IRON_ORE_FINES', 'Iron Ore Fines'), ('LIMESTONE', 'Limestone'), ('DOLOMITE', 'Dolomite'), ('COAL', 'Coal'), ('COKE', 'Coke'), ('COKE_FINES', 'Coke Fines'), ('SINTER', 'Sinter'), ('SINTER_FINES', 'Sinter Fines'), ('PELLET', 'Pellet'), ('LUMP_ORE', 'Lump Ore'), ('QUARTZITE', 'Quartzite'), ('SLAG', 'Slag'), ('BASE_MIX', 'Base Mix'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='area23operation',
            name='feeding_material',
            field=models.CharField(choices=[('IRON_ORE', 'Iron Ore'), ('IRON_ORE_FINES', 'Iron Ore Fines'), ('LIMESTONE', 'Limestone'), ('DOLOMITE', 'Dolomite'), ('COAL', 'Coal'), ('COKE', 'Coke'), ('COKE_FINES', 'Coke Fines'), ('SINTER', 'Sinter'), ('SINTER_FINES', 'Sinter Fines'), ('PELLET', 'Pellet'), ('LUMP_ORE', 'Lump Ore'), ('QUARTZITE', 'Quartzite'), ('SLAG', 'Slag'), ('BASE_MIX', 'Base Mix'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='area23operation',
            name='receiving_material',
            field=models.CharField(choices=[('IRON_ORE', 'Iron Ore'), ('IRON_ORE_FINES', 'Iron Ore Fines'), ('LIMESTONE', 'Limestone'), ('DOLOMITE', 'Dolomite'), ('COAL', 'Coal'), ('COKE', 'Coke'), ('COKE_FINES', 'Coke Fines'), ('SINTER', 'Sinter'), ('SINTER_FINES', 'Sinter Fines'), ('PELLET', 'Pellet'), ('LUMP_ORE', 'Lump Ore'), ('QUARTZITE', 'Quartzite'), ('SLAG', 'Slag'), ('BASE_MIX', 'Base Mix'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
